"use client";

import RetinaUpload from "../components/RetinaUpload";

export default function Home() {
  return (
    <main className="min-h-screen" style={{ backgroundColor: "var(--bg)" }}>
      {/* Clinical header */}
      <header style={{ backgroundColor: "var(--clinic-navy)" }}>
        <div className="max-w-3xl mx-auto px-6 py-8 flex items-center gap-4">
          <div
            className="w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0"
            style={{ backgroundColor: "var(--clinic-teal)" }}
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
              <circle cx="12" cy="12" r="3.5" fill="white" />
              <path
                d="M2 12c2.5-5 6.5-8 10-8s7.5 3 10 8c-2.5 5-6.5 8-10 8s-7.5-3-10-8z"
                stroke="white"
                strokeWidth="1.6"
                fill="none"
              />
            </svg>
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white leading-tight">RetinaScan</h1>
            <p className="text-sm" style={{ color: "#8fb8cc" }}>
              AI-Assisted Diabetic Retinopathy Screening
            </p>
          </div>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-10">
        {/* Clinical disclaimer banner */}
        <div
          className="rounded-xl p-4 mb-8 flex gap-3 items-start"
          style={{ backgroundColor: "#fff8ec", border: "1px solid #f0d9a8" }}
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" className="flex-shrink-0 mt-0.5">
            <circle cx="12" cy="12" r="10" stroke="#a3721a" strokeWidth="1.6" />
            <path d="M12 8v5" stroke="#a3721a" strokeWidth="1.6" strokeLinecap="round" />
            <circle cx="12" cy="16" r="0.8" fill="#a3721a" />
          </svg>
          <p className="text-sm leading-relaxed" style={{ color: "#7a5613" }}>
            <strong>This is a screening aid, not a diagnosis.</strong> Results
            are generated by a machine learning model for demonstration
            purposes and must not replace professional evaluation by a
            qualified eye care specialist.
          </p>
        </div>

        <div className="clinic-card rounded-2xl p-8">
          <h2 className="text-lg font-semibold mb-1" style={{ color: "var(--clinic-navy)" }}>
            Upload Fundus Photograph
          </h2>
          <p className="text-sm mb-6" style={{ color: "var(--text-muted)" }}>
            Upload a retina scan image to screen for signs of diabetic
            retinopathy across five severity levels.
          </p>
          <RetinaUpload />
        </div>

        <p className="text-xs text-center mt-8" style={{ color: "var(--text-muted)" }}>
          Model trained on the APTOS 2019 dataset · Not FDA approved · For demonstration only
        </p>
      </div>
    </main>
  );
}